version: '3.9'

services:
  insights-postgres:
    image: postgres:16
    container_name: insights-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: insightsdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - insights-net

  node-analytics:
    build: ./node-analytics
    container_name: node-analytics
    restart: always
    depends_on:
      - insights-postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@insights-postgres:5432/insightsdb
      PORT: 4000
    ports:
      - "4000:4000"
    networks:
      - insights-net

  backend-dotnet:
    build: ./backend-dotnet
    container_name: backend-dotnet
    restart: always
    depends_on:
      - insights-postgres
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ConnectionStrings__DefaultConnection: "Host=insights-postgres;Port=5432;Database=insightsdb;Username=postgres;Password=postgres"
      ASPNETCORE_URLS: "http://+:8080"
    ports:
      - "5000:8080"
    networks:
      - insights-net

  react-frontend:
    build: ./frontend-react
    container_name: react-frontend
    restart: always
    depends_on:
      - backend-dotnet
      - node-analytics
    ports:
      - "5173:80"
    networks:
      - insights-net

volumes:
  postgres_data:

networks:
  insights-net:

