name: CD Pipeline

on:
  workflow_run:
    workflows: ["CI Pipeline"]
    types:
      - completed

jobs:
  deploy:
    name: 🚀 Deploy to EC2
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: 🔐 SSH into EC2 and deploy latest version
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "🔄 Pulling latest repo code..."
            cd ~/data-insights-dashboard
            git pull origin main

            echo "🛑 Stopping old containers..."
            sudo docker-compose -f docker-compose.prod.yml down

            echo "⬇️ Pulling latest images from Docker Hub..."
            sudo docker-compose -f docker-compose.prod.yml pull

            echo "🚀 Starting new containers..."
            sudo docker-compose -f docker-compose.prod.yml up -d

            echo "🧹 Cleaning unused Docker data..."
            sudo docker system prune -f

            echo "✅ Deployment completed successfully on EC2!"
