name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: insightsdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install backend dependencies
        working-directory: node-analytics
        run: npm install

      - name: Run backend tests (skip if none)
        working-directory: node-analytics
        run: echo "No tests yet"

      - name: Install frontend dependencies
        working-directory: frontend-react
        run: npm install

      - name: Build frontend
        working-directory: frontend-react
        run: npm run build

      - name: Build Docker images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/insights-backend ./node-analytics
          docker build -t ${{ secrets.DOCKER_USERNAME }}/insights-frontend ./frontend-react

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker images
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/insights-backend
          docker push ${{ secrets.DOCKER_USERNAME }}/insights-frontend
